trigger: none
stages:
- stage: CI
  jobs:
  - job: Job_1
    displayName:  Build Agent 
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.csproj'
      testsolution: '**/*[Tt]ests/*.csproj'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - checkout: self
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(solution)'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        arguments: '--configuration $(BuildConfiguration)'
        projects: '$(solution)'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
       command: test
       arguments: '--configuration $(BuildConfiguration)'
       projects: '$(testsolution)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
       command: publish
       publishWebProjects: True
       arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
       zipAfterPublish: True
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Dacpac'
      inputs:
       SourceFolder: Dacpac
       TargetFolder: '$(build.artifactstagingdirectory)/Dacpac'
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Terraform copy'
      inputs:
       SourceFolder: terraform
       TargetFolder: '$(build.artifactstagingdirectory)/Terraform'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
       PathtoPublish: '$(build.artifactstagingdirectory)'
       ArtifactName: 'drop'
       

